/**
NOT TESTED ON REAL JENKINS ENVIRONMENT. YET! :)
**/

// shenbag in case shared libs are used
#!/usr/bin/env groovy

// main body
pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        // source
        sh 'This will retrieve sourcecode for ecosystem...'
        checkout scm
      }
    }
    stage('Provision - Contenarize - Build - Deploy') {
      // workflow validation
      timeout(time: 30, unit: 'SECONDS') {
        input {
          message "Should we continue the execution?",
          ok "Yes, we should.",
          submitter "root",
          parameters {
              [booleanParam(defaultValue: true, 
                          description: 'Yes, continue.',name: 'Yes?')]
          }
        }
      }
      steps {
        // aws resources
        sh 'This will preprae ecosystem and build React Frontend for the defined backend...'
        dir('../.') {
          sh 'terraform fmt && terraform validate && terraform plan'
          sh 'terraform apply'
        }
        sh 'sleep 600'
        // aws k8s self-managed cluster
        dir('../.k8sconfig') {
          sh 'kubectl apply --validate=true --dry-run=true --filename=task_2.yaml'
          sh 'kubectl apply -f task_2.yaml'
        }
        sh 'sleep 600'
        // react application
        dir('../.') {
          sh 'npm run build'
          sh 'npm run deploy'
          sh 'npm publish --dry-run'
          sh 'npm publish'
        }
      }
    } 
  }
}
